### ISSUE TITLE
毕业论文答辩完了 所以接下来呢？

### ISSUE THREAD

**Issue by vinthony** [vinthony/vinthony.github.io#21]
不经意之间，我已经开了很多坑了。。。。 = =

为了不开新的坑 = = （ 脑洞不要太大。。。

现决定，在一年之内填下如下的坑,排名不分先后：

- [ ]  编译原理
- [ ]  SICP [answer](https://github.com/vinthony/sicp)
- [ ]  [canvas plus](https://github.com/OceanRipple/canvasplus.js)
- [ ] [爬虫框架](https://github.com/vinthony/racpider)
- [ ] Haskell

**Comment by plusmancn** [comment]
很酷额

**Comment by vinthony** [comment]
@plusmancn   = = 谢谢！

**Comment by luckyScript** [comment]
快到一年了 ^_^

**Comment by vinthony** [comment]
@luckyScript 感觉自己的脸被打的好肿。。。

**Comment by koi646** [comment]
围观...
